<?php
/**
 * Created by PhpStorm.
 * User: karpovi4
 * Date: 12.02.16
 * Time: 13:46
 */

namespace frontend\controllers;

use common\models\Activity;
use frontend\models\Present;
use Yii;
use yii\web\Controller;


class BaseController extends Controller {

	public function init() {
		$presents = Present::getPresentsList();
		$activity = Activity::find()->orderBy('RAND()')->one();

		$this->getView()->params = [
			'presents' => $presents,
			'activity' => $activity,
		];
		parent::init(); // TODO: Change the autogenerated stub
	}
}